name: 'Setup Android and JDK 17'
description: 'Set up Android environment variables, update apt, install JDK 17, and display environment variables.'
author: Gabriel Reinisch Faleiro

branding:
  icon: "terminal"
  color: "purple"
  
runs:
  using: 'composite'
  steps:
    - name: Set up Android environment variables
      shell: bash
      run: |
        echo "Setting up Android environment variables"
        echo "ANDROID_HOME=~/Android/Sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=~/Android/Sdk" >> $GITHUB_ENV
        echo "ANDROID_AVD_HOME=/home/runner/.config/.android/avd/" >> $GITHUB_ENV

    - name: Update apt
      shell: bash
      run: sudo apt-get update

    - name: Install JDK 17
      shell: bash
      run: |
        sudo apt-get install -y openjdk-17-jdk
