name: 'Setup Android and JDK 17'

description: 'Set up Android environment variables, update apt, install JDK 17, and display environment variables.'

runs:
  using: 'composite'
  steps:
    - name: Set up Android environment variables
      run: |
        echo "Setting up Android environment variables"
        echo "ANDROID_HOME=~/Android/Sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=~/Android/Sdk" >> $GITHUB_ENV
        echo "ANDROID_AVD_HOME=/home/runner/.config/.android/avd/" >> $GITHUB_ENV

    - name: Update apt
      run: sudo apt-get update

    - name: Install JDK 17
      run: |
        sudo apt-get install -y openjdk-17-jdk

    - name: Check Java version
      run: java -version

    - name: Display environment variables
      run: echo "ANDROID_HOME=$ANDROID_HOME, ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT, ANDROID_AVD_HOME=$ANDROID_AVD_HOME"
