name: TEST AVD Action ubuntu

on:
    push:
      branches:
        - develop
    pull_request:
      branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Install and Set JDK 17 manually
      run: |
        sudo apt-get install -y openjdk-17-jdk
        sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
        sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac &
        java -version
    
    - name: Appium & AVD action ubuntu (a&a-u)
      uses: fahleiro/appium-avd-action-ubuntu@appium-avd-action-ubuntu-1.1.0
                  
    - name: TESTING JAVA
      run: java -version

    - name: TESTING ANDROID ENVIRONMENTS
      run: | 
          echo $ANDROID_HOME
          echo $ANDROID_SDK_ROOT
          echo $ANDROID_AVD_HOME

    - name: Test adb devices
      run: |
          ~/Android/Sdk/platform-tools/adb devices

          
      
