# name: TEST AVD Action ubuntu

# on:
#   push:
#     branches:
#       - develop
#   pull_request:
#     branches: [ "develop" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       ANDROID_HOME: ~/Android/Sdk
#       ANDROID_SDK_ROOT: ~/Android/Sdk
#       ANDROID_AVD_HOME: /home/runner/.config/.android/avd/

#     steps:
#     - name: Set up JDK 17
#       uses: actions/setup-java@v4
#       with:
#         java-version: '17'
#         distribution: 'adopt'

#     - name: TESTING JAVA
#       run: |
#           java -version
    
#     - name: Appium & AVD action ubuntu (a&a-u)
#       uses: fahleiro/appium-avd-action-ubuntu@appium-avd-action-ubuntu-1.1.1
            
                  
#     - name: TESTING ANDROID ENVIRONMENTS
#       run: | 
#           echo $ANDROID_HOME
#           echo $ANDROID_SDK_ROOT
#           echo $ANDROID_AVD_HOME

#     - name: Test adb devices
#       run: |
#           ~/Android/Sdk/platform-tools/adb devices
