name: TEST AVD Action ubuntu

on:
    push:
      branches:
        - develop
    pull_request:
      branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Appium & AVD action ubuntu (a&a-u)
      uses: fahleiro/appium-avd-action-ubuntu@appium-avd-action-ubuntu-1.0.4
    
    - name: Testing adb
      run: adb devices
