name: TEST AVD Action ubuntu

on:
    push:
      branches:
        - develop
    pull_request:
      branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Appium & AVD action ubuntu (a&a-u)
      uses: fahleiro/appium-avd-action-ubuntu@appium-avd-action-ubuntu-1.1.0
                  
    - name: TESTING JAVA
      run: java -version

    - name: TESTING ANDROID ENVIRONMENTS
      run: | 
          echo $ANDROID_HOME
          echo $ANDROID_SDK_ROOT
          echo $ANDROID_AVD_HOME

    - name: Test adb devices
      run: |
          ~/Android/Sdk/platform-tools/adb devices

          
      
