name: TEST AVD Action ubuntu

on:
    push:
      branches:
        - develop
    pull_request:
      branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Android and JDK 17
      uses: fahleiro/appium-avd-action-ubuntu@test-jdk-alternative-17
            
    - name: TESTING JAVA
      run: java -version

    - name: TESTING ANDROID ENVIRONMENTS
      run: | 
          echo $ANDROID_HOME
          echo $ANDROID_SDK_ROOT
          echo $ANDROID_AVD_HOME
      
