name: TEST AVD Action ubuntu

on:
    push:
      branches:
        - develop
    pull_request:
      branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Android and JDK 17
      uses: fahleiro/appium-avd-action-ubuntu@test-setup-android-jdk-17     
    
    - name: TESTING JAVA
      run: java -version
